


### Test POST a Person without data
POST http://localhost:3001/api/persons
Content-Type: application/json

{}

### Test POST a Person with data
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test API Name",
  "number": "39-23-1724560"
}

### Test GET all Person
GET http://localhost:3001/api/persons

### Test GET a existing Person
GET http://localhost:3001/api/persons/1

### Test GET a non existing Person
GET http://localhost:3001/api/persons/2129

### Test DELETE an existing Person
DELETE http://localhost:3001/api/persons/1

### Test DELETE a non existing Person
DELETE http://localhost:3001/api/persons/2129